# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
from io import BytesIO
from datetime import datetime
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from openai import OpenAI
import os
import io
from PyPDF2 import PdfReader
import graphviz
from streamlit_mermaid import st_mermaid

# ตั้งค่าหน้าเพจ
st.set_page_config(page_title="Planning Studio (+ Findings Suggestions)", page_icon="🧭", layout="wide")

# ----------------- ⚙️ การตั้งค่ากลาง -----------------
with st.sidebar:
    st.title("⚙️ การตั้งค่ากลาง")
    # ... (ส่วนนี้เหมือนเดิม) ...

# ----------------- ฟังก์ชันต่างๆ -----------------
def init_state():
    ss = st.session_state
    ss.setdefault("plan", {"plan_id": "PLN-" + datetime.now().strftime("%y%m%d-%H%M%S"),"plan_title": ""}) # (ย่อ)
    logic_cols = ["item_id","plan_id","type","description","metric","unit","target","source"]
    ss.setdefault("logic_items", pd.DataFrame(columns=logic_cols))
    # ... (ส่วนที่เหลือของ init_state เหมือนเดิม) ...

def next_id(prefix, df, col):
    if df.empty: return f"{prefix}-001"
    nums = [int(str(x).split("-")[-1]) for x in df[col] if str(x).split("-")[-1].isdigit()]
    n = max(nums) + 1 if nums else 1
    return f"{prefix}-{n:03d}"

def create_mermaid_flowchart(df: pd.DataFrame):
    type_to_id = {
        "Objective": "Objective", "Input": "Input", "Activity": "Activity",
        "Output": "Output", "Outcome": "Outcome", "Impact": "Impact"
    }
    sequence = ["Objective", "Input", "Activity", "Output", "Outcome", "Impact"]
    mermaid_string = "graph LR\n"
    styles = {
        "Objective": "fill:#E6E6FA,stroke:#333,stroke-width:2px",
        "Input": "fill:#a9def9,stroke:#333,stroke-width:2px",
        "Activity": "fill:#e4c1f9,stroke:#333,stroke-width:2px",
        "Output": "fill:#fcf6bd,stroke:#333,stroke-width:2px",
        "Outcome": "fill:#d0f4de,stroke:#333,stroke-width:2px",
        "Impact": "fill:#ff99c8,stroke:#333,stroke-width:2px",
        "E_Box": "fill:#FFDAB9,stroke:#e67300,stroke-width:2px,color:#e67300",
    }
    for key, value in styles.items():
        mermaid_string += f"  classDef {key}Style {value}\n"
    nodes_exist = []
    for item_type in sequence:
        items_df = df[df['type'] == item_type]
        if not items_df.empty:
            node_id = type_to_id[item_type]
            header = f'<strong>{item_type}</strong>'
            description_lines = []
            for _, row in items_df.iterrows():
                desc = str(row.get('description', '') or ''); metric = str(row.get('metric', '') or '')
                target = str(row.get('target', '') or ''); unit = str(row.get('unit', '') or '')
                number = target if target else metric
                line_parts = [f"• {desc}"]
                if number: line_parts.append(number)
                if unit: line_parts.append(unit)
                description_lines.append(" ".join(part for part in line_parts if part))
            content = f"{header}<br/>" + "<br/>".join(description_lines)
            mermaid_string += f'  {node_id}["{content}"]\n'
            mermaid_string += f'  class {node_id} {node_id}Style\n'
            nodes_exist.append(node_id)
    if len(nodes_exist) > 1:
        mermaid_string += "  " + " --> ".join(nodes_exist) + "\n"
    if len(nodes_exist) >= 3:
        mermaid_string += "\n  %% 3E Boxes Autogenerated\n"
        if "Input" in nodes_exist:
            mermaid_string += '  Economy["ประหยัด (Economy)"]\n'; mermaid_string += "  Economy --> Input\n"; mermaid_string += "  class Economy E_BoxStyle\n"
        if "Input" in nodes_exist and "Output" in nodes_exist:
            mermaid_string += '  Efficiency["ประสิทธิภาพ (Efficiency)"]\n'; mermaid_string += "  Input --> Efficiency --> Output\n"; mermaid_string += "  class Efficiency E_BoxStyle\n"
        effectiveness_connections = []
        if "Objective" in nodes_exist: effectiveness_connections.append("Objective")
        if "Output" in nodes_exist: effectiveness_connections.append("Output")
        if effectiveness_connections:
            mermaid_string += '  Effectiveness["ประสิทธิผล (Effectiveness)"]\n'
            for node in effectiveness_connections: mermaid_string += f"  {node} --> Effectiveness\n"
            if "Outcome" in nodes_exist: mermaid_string += "  Effectiveness --> Outcome\n"
            if "Impact" in nodes_exist: mermaid_string += "  Effectiveness --> Impact\n"
            mermaid_string += "  class Effectiveness E_BoxStyle\n"
    return mermaid_string

# (ฟังก์ชันอื่นๆ ที่ไม่เกี่ยวข้องจะถูกย่อไว้)
# ...

init_state()
plan = st.session_state["plan"]
logic_df = st.session_state["logic_items"]
# ...

st.title("🧭 Planning Studio – Performance Audit")
# ...

tab_plan, tab_logic, tab_method, tab_kpi, tab_risk, tab_issue, tab_preview, tab_assist, tab_chatbot = st.tabs(["1. ระบุ แผน & 6W2H", "2. ระบุ Logic Model", "3. ระบุ Methods", "4. ระบุ KPIs", "5. ระบุ Risks", "6. 🔍ค้นหาข้อตรวจพบที่ผ่านมา", "7. 📋สรุปข้อมูล (Preview)", "8. ✨PA Assistant แนะนำประเด็น", "9. 💬 PA Chat"]) 

with tab_plan:
    # ... (โค้ดใน tab_plan เหมือนเดิมทั้งหมด) ...
    pass

#! <<< START: แก้ไข Layout และ Logic ใน Tab นี้ทั้งหมด
with tab_logic:
    st.subheader("ระบุ Logic Model")
    st.info("""
    **วิธีใช้งาน:** แก้ไขข้อมูลในตารางได้โดยตรง | **เพิ่มแถว** โดยกดปุ่ม 'Add row' ด้านล่าง | **ลบแถว** โดยติ๊ก ✅ หน้าแถวแล้วกด 🗑️
    """)

    # --- 1. ส่วนตารางแก้ไขข้อมูล (Data Editor) ---
    with st.container():
        edited_df = st.data_editor(
            st.session_state.logic_items,
            column_config={
                "type": st.column_config.SelectboxColumn("ประเภท", options=["Objective", "Input", "Activity", "Output", "Outcome", "Impact"], required=True),
                "description": st.column_config.TextColumn("คำอธิบาย/รายละเอียด", required=True),
                "metric": st.column_config.TextColumn("ตัวชี้วัด/metric"),
                "target": st.column_config.TextColumn("เป้าหมาย"),
                "unit": st.column_config.TextColumn("หน่วย"),
                "source": st.column_config.TextColumn("แหล่งข้อมูล"),
                "item_id": st.column_config.TextColumn("ID", disabled=True),
                "plan_id": st.column_config.TextColumn("Plan ID", disabled=True),
            },
            use_container_width=True,
            hide_index=True,
            num_rows="dynamic", # เปิดใช้งานการเพิ่ม/ลบแถวในตัว
            key="logic_editor"
        )

        # --- ส่วนจัดการข้อมูลหลังการแก้ไข ---
        if edited_df is not None:
            for i, row in enumerate(edited_df):
                # สร้าง ID สำหรับแถวใหม่ที่ยังไม่มี ID
                if pd.isna(row.get('item_id')) or row.get('item_id') == '':
                    temp_df = pd.DataFrame(edited_df).dropna(subset=['item_id'])
                    edited_df[i]['item_id'] = next_id("LG", temp_df, "item_id")
                if pd.isna(row.get('plan_id')) or row.get('plan_id') == '':
                     edited_df[i]['plan_id'] = plan["plan_id"]
            
            st.session_state.logic_items = pd.DataFrame(edited_df)

        # --- ปุ่ม Reset ที่มุมขวาล่าง ---
        cols = st.columns([0.85, 0.15])
        with cols[1]:
            if st.button("🧹 ล้างทั้งหมด (Reset)", use_container_width=True):
                # สร้าง DataFrame ว่างเปล่าที่มีคอลัมน์ครบถ้วน
                empty_df = pd.DataFrame(columns=st.session_state.logic_items.columns)
                st.session_state.logic_items = empty_df
                st.rerun()

    st.markdown("---")

    # --- 2. ส่วนแสดง Flowchart ---
    st.subheader("📊 Flowchart Logic Model")
    with st.container(border=True):
        if not st.session_state.logic_items.empty:
            try:
                # --- คำนวณความสูงของ Chart แบบ Dynamic ---
                base_height = 300
                num_rows = len(st.session_state.logic_items)
                num_types = st.session_state.logic_items['type'].nunique()
                # เพิ่มความสูงตามจำนวนรายการและจำนวนประเภท เพื่อให้มีพื้นที่พอสำหรับกล่อง
                dynamic_height = base_height + (num_rows * 20) + (num_types * 50)
                chart_height = min(max(dynamic_height, 400), 1200) # กำหนดความสูงต่ำสุดและสูงสุด
                
                mermaid_chart = create_mermaid_flowchart(st.session_state.logic_items)
                st_mermaid(mermaid_chart, height=f"{chart_height}px")
            except Exception as e:
                st.error(f"ไม่สามารถสร้าง Flowchart ได้: {e}")
        else:
            st.info("กรุณาเพิ่มข้อมูลในตารางด้านบนเพื่อสร้าง Flowchart")

#! <<< END: สิ้นสุดการแก้ไข Tab Logic

# ... (โค้ดของ Tab ที่เหลือเหมือนเดิมทั้งหมด) ...
