# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
from io import BytesIO
from datetime import datetime
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from openai import OpenAI
import os
import io
from PyPDF2 import PdfReader
import graphviz
from streamlit_mermaid import st_mermaid

# ตั้งค่าหน้าเพจ
st.set_page_config(page_title="Planning Studio (+ Findings Suggestions)", page_icon="🧭", layout="wide")

# (ส่วนของการตั้งค่าและฟังก์ชันอื่นๆ เหมือนเดิม)
# ...

#! <<< START: แก้ไขฟังก์ชันนี้ให้เสถียรขึ้น
def create_mermaid_flowchart(df: pd.DataFrame):
    """
    สร้างโค้ด Mermaid โดยใช้ Layout แบบบนลงล่าง (TD) และตัด Subgraph ที่ซับซ้อนออก
    """
    type_to_id = {
        "Objective": "Objective", "Input": "Input", "Activity": "Activity",
        "Output": "Output", "Outcome": "Outcome", "Impact": "Impact"
    }
    sequence = ["Objective", "Input", "Activity", "Output", "Outcome", "Impact"]
    
    mermaid_string = "graph TD\n"
    
    styles = {
        "Objective": "fill:#E6E6FA,stroke:#333,stroke-width:2px",
        "Input": "fill:#a9def9,stroke:#333,stroke-width:2px",
        "Activity": "fill:#e4c1f9,stroke:#333,stroke-width:2px",
        "Output": "fill:#fcf6bd,stroke:#333,stroke-width:2px",
        "Outcome": "fill:#d0f4de,stroke:#333,stroke-width:2px",
        "Impact": "fill:#ff99c8,stroke:#333,stroke-width:2px",
        "E_Box": "fill:#FFDAB9,stroke:#e67300,stroke-width:2px,color:#e67300",
    }
    for key, value in styles.items():
        mermaid_string += f"  classDef {key}Style {value}\n"
        
    nodes_exist = []
    for item_type in sequence:
        items_df = df[df['type'] == item_type]
        if not items_df.empty:
            node_id = type_to_id[item_type]
            header = f'<strong>{item_type}</strong>'
            description_lines = []
            for _, row in items_df.iterrows():
                desc = str(row.get('description', '') or ''); metric = str(row.get('metric', '') or '')
                target = str(row.get('target', '') or ''); unit = str(row.get('unit', '') or '')
                number = target if target else metric
                line_parts = [f"• {desc}"]
                if number: line_parts.append(number)
                if unit: line_parts.append(unit)
                description_lines.append(" ".join(part for part in line_parts if part))
            
            content_body = "<br/>".join(description_lines)
            content = f"<div style='text-align: left;'>{header}<br/>{content_body}</div>"
            mermaid_string += f'  {node_id}["{content}"]\n'
            mermaid_string += f'  class {node_id} {node_id}Style\n'
            nodes_exist.append(node_id)
    
    # --- ส่วนการเชื่อมเส้น ---
    # 1. เชื่อมเส้นหลัก
    if len(nodes_exist) > 1:
        mermaid_string += "  " + " --> ".join(nodes_exist) + "\n"

    # 2. สร้างและเชื่อม 3E
    if len(nodes_exist) >= 3:
        mermaid_string += "\n  %% 3E Boxes Autogenerated\n"
        
        # สร้าง Node ของ 3E ก่อน
        if "Input" in nodes_exist:
            mermaid_string += '  Economy["ประหยัด (Economy)"]\n'
            mermaid_string += "  class Economy E_BoxStyle\n"
        if "Input" in nodes_exist and "Output" in nodes_exist:
            mermaid_string += '  Efficiency["ประสิทธิภาพ (Efficiency)"]\n'
            mermaid_string += "  class Efficiency E_BoxStyle\n"
        if "Objective" in nodes_exist or "Output" in nodes_exist:
            mermaid_string += '  Effectiveness["ประสิทธิผล (Effectiveness)"]\n'
            mermaid_string += "  class Effectiveness E_BoxStyle\n"
        
        # เชื่อมเส้นของ 3E ทีหลัง
        if "Input" in nodes_exist:
            mermaid_string += "  Economy --> Input\n"
            mermaid_string += "  Input --> Efficiency\n"
            mermaid_string += "  Efficiency --> Output\n"

        if "Objective" in nodes_exist or "Output" in nodes_exist:
            if "Objective" in nodes_exist:
                mermaid_string += "  Objective --> Effectiveness\n"
            if "Output" in nodes_exist:
                mermaid_string += "  Output --> Effectiveness\n"
            if "Outcome" in nodes_exist:
                mermaid_string += "  Effectiveness --> Outcome\n"
            if "Impact" in nodes_exist:
                mermaid_string += "  Effectiveness --> Impact\n"
            
    return mermaid_string
#! <<< END: สิ้นสุดการแก้ไขฟังก์ชัน

# (โค้ดส่วนที่เหลือของไฟล์เหมือนเดิมทั้งหมด)
# ...
# init_state(), st.title(), tabs, etc.

# ----------------- ส่วนของ tab_logic ที่จะรันโค้ดด้านบน -----------------
# with tab_logic:
#     ... (เหมือนเดิม) ...
#     mermaid_chart = create_mermaid_flowchart(st.session_state.logic_items)
#     st_mermaid(mermaid_chart, height=f"{chart_height}px")
#     ...
